from datetime import datetime
from app import db

class Transaction(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    currency = db.Column(db.String(10))
    location = db.Column(db.String(50))
    region = db.Column(db.String(50))
    sales_person = db.Column(db.String(100))
    customer_name = db.Column(db.String(200))
    product = db.Column(db.String(100))
    nature_of_business = db.Column(db.String(100))
    bu = db.Column(db.String(50))
    partner_location = db.Column(db.String(100))
    partner = db.Column(db.String(100))
    type = db.Column(db.String(50))
    psm = db.Column(db.String(100))
    partner_led = db.Column(db.Boolean)
    partner_account_manager_name = db.Column(db.String(100))
    designation = db.Column(db.String(100))
    email_id = db.Column(db.String(100))
    phone_number = db.Column(db.String(20))
    why_did_they_buy = db.Column(db.Text)
    inv_date = db.Column(db.DateTime)
    qtr = db.Column(db.String(10))
    year = db.Column(db.String(10))
    inv_value = db.Column(db.Float)
    gp = db.Column(db.Float)
    comments = db.Column(db.Text)

class TeleSales(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    rep_name = db.Column(db.String(100))
    total_calls_made = db.Column(db.Integer)
    new_calls = db.Column(db.Integer)
    follow_up_calls = db.Column(db.Integer)
    not_connected = db.Column(db.Integer)
    connected_buy_not_interested = db.Column(db.Integer)
    connected_and_asked_to_call_back = db.Column(db.Integer)
    connected_call = db.Column(db.Integer)
    emails_sent = db.Column(db.Integer)
    new_emails = db.Column(db.Integer)
    follow_up_emails = db.Column(db.Integer)
    total_linkedin = db.Column(db.Integer)
    linkedin_new_connect = db.Column(db.Integer)
    linkedin_followups = db.Column(db.Integer)
    edms_sent = db.Column(db.Integer)
    appointments_set = db.Column(db.Integer)
    demos_scheduled = db.Column(db.Integer)
    meetings_held = db.Column(db.Integer)
    deals_closed = db.Column(db.Integer)
    notes_updated_in_crm = db.Column(db.Boolean)
    comments_notes = db.Column(db.Text)

class Renewal(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.DateTime)
    specialist_name = db.Column(db.String(100))
    partners_touched = db.Column(db.Integer)
    calls_made = db.Column(db.Integer)
    emails_sent = db.Column(db.Integer)
    renewals_due = db.Column(db.Integer)
    renewals_closed = db.Column(db.Integer)
    at_risk_accounts_engaged = db.Column(db.Integer)
    upsell_opportunities_identified = db.Column(db.Integer)
    total_arr_renewed = db.Column(db.Float)
    notes_updated_in_crm = db.Column(db.Boolean)
    churn_risk_notes = db.Column(db.Text)
    productivity_comments = db.Column(db.Text)

class RenewalData(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    currency = db.Column(db.String(10))
    location = db.Column(db.String(50))
    sales_person = db.Column(db.String(100))
    customer_name = db.Column(db.String(200))
    product = db.Column(db.String(100))
    nature_of_business = db.Column(db.String(100))
    bu = db.Column(db.String(50))
    partner_location = db.Column(db.String(100))
    partner = db.Column(db.String(100))
    psm = db.Column(db.String(100))
    partner_account_manager_name = db.Column(db.String(100))
    designation = db.Column(db.String(100))
    email_id = db.Column(db.String(100))
    phone_number = db.Column(db.String(20))
    date_of_renewal = db.Column(db.DateTime)
    last_year_invoice_date = db.Column(db.DateTime)
    last_year_invoice_value = db.Column(db.Float)
    last_year_margins = db.Column(db.Float)
    this_year_technobind_price = db.Column(db.Float)
    this_year_partner_price = db.Column(db.Float)
    status = db.Column(db.String(50))
    comments = db.Column(db.Text)

class ProductLookup(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product_name = db.Column(db.String(100))
    primary_industry_focus = db.Column(db.Text)
    ideal_customer_profiles = db.Column(db.Text)
    persona = db.Column(db.String(100))
    role = db.Column(db.String(100))
    key_concerns = db.Column(db.Text)
    problem_statement = db.Column(db.Text)
    value_propositions = db.Column(db.Text)

class Partner(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    company_name = db.Column(db.String(200))
    partner_type = db.Column(db.String(100))
    website_url = db.Column(db.String(200))
    headquarters_location = db.Column(db.String(100))
    hq_address = db.Column(db.Text)
    regional_presence = db.Column(db.String(200))
    partner_tier = db.Column(db.String(50))
    top_oems = db.Column(db.Text)
    industry_focus = db.Column(db.Text)
    tech_stack_focus = db.Column(db.Text)
    tech_stack_expertise = db.Column(db.Text)
    vendor_certifications = db.Column(db.Text)
    key_services_offered = db.Column(db.Text)
    client_size_focus = db.Column(db.String(50))
    years_in_operation = db.Column(db.Integer)
    number_of_employees = db.Column(db.Integer)
    annual_revenue_est = db.Column(db.Float)
    contact_person_name = db.Column(db.String(100))
    contact_email = db.Column(db.String(100))
    contact_phone = db.Column(db.String(20))
    linkedin_profile = db.Column(db.String(200))
    partner_status = db.Column(db.String(50))
    last_engagement_date = db.Column(db.DateTime)
    notes_comments = db.Column(db.Text)

class PartnerContact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    contact_name = db.Column(db.String(100))
    job_title = db.Column(db.String(100))
    email_address = db.Column(db.String(100))
    phone_number = db.Column(db.String(20))
    linkedin_profile = db.Column(db.String(200))
    company_name = db.Column(db.String(200))
    company_website = db.Column(db.String(200))
    company_tier = db.Column(db.String(50))
    department = db.Column(db.String(100))
    location_city_country = db.Column(db.String(100))
    primary_region = db.Column(db.String(100))
    products_handled = db.Column(db.Text)
    is_decision_maker = db.Column(db.Boolean)
    date_of_birth = db.Column(db.DateTime)
    influence_level = db.Column(db.String(20))
    engagement_type = db.Column(db.String(100))
    first_contact_date = db.Column(db.DateTime)
    last_contact_date = db.Column(db.DateTime)
    preferred_contact_method = db.Column(db.String(50))
    communication_status = db.Column(db.String(50))
    notes_history = db.Column(db.Text)

class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    organization_name = db.Column(db.String(200))
    organization_founded_year = db.Column(db.Integer)
    organization_market_cap = db.Column(db.Float)
    phone_number_1 = db.Column(db.String(20))
    phone_number_2 = db.Column(db.String(20))
    phone_status = db.Column(db.String(20))
    organization_primary_domain = db.Column(db.String(100))
    city = db.Column(db.String(100))
    state = db.Column(db.String(100))
    country = db.Column(db.String(100))
    person_name = db.Column(db.String(100))
    first_name = db.Column(db.String(50))
    last_name = db.Column(db.String(50))
    person_linkedin_url = db.Column(db.String(200))
    designation = db.Column(db.String(100))
    email_status = db.Column(db.String(20))
    email = db.Column(db.String(100))
    organization_facebook_url = db.Column(db.String(200))
    organization_linkedin_url = db.Column(db.String(200))
    organization_twitter_url = db.Column(db.String(200))
    organization_website_url = db.Column(db.String(200))
    employee_size = db.Column(db.Integer)
    primary_industry = db.Column(db.String(100))
    comments = db.Column(db.Text)

class Company(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    company = db.Column(db.String(200))
    head_office_location = db.Column(db.String(100))
    primary_industry = db.Column(db.String(100))
    industry = db.Column(db.Text)
    sub_industry = db.Column(db.String(100))
    type = db.Column(db.String(50))
    location = db.Column(db.String(100))
    employee_count = db.Column(db.String(50))
    revenue_range = db.Column(db.String(50))
    num_employees = db.Column(db.Integer)
    industry2 = db.Column(db.String(100))
    website = db.Column(db.String(200))
    company_linkedin_url = db.Column(db.String(200))
    facebook_url = db.Column(db.String(200))
    twitter_url = db.Column(db.String(200))
    keywords = db.Column(db.Text)
    company_phone = db.Column(db.String(20))
    seo_description = db.Column(db.Text)
    technologies = db.Column(db.Text)
    total_funding = db.Column(db.Float)
    latest_funding = db.Column(db.String(100))
    latest_funding_amount = db.Column(db.Float)
    last_raised_at = db.Column(db.DateTime)
    annual_revenue = db.Column(db.Float)
    number_of_retail_locations = db.Column(db.Integer)
    short_description = db.Column(db.Text)
    founded_year = db.Column(db.Integer)
    comments = db.Column(db.Text)